-- Migration: create leads table (id generated by Node)
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT,
  course TEXT,
  source TEXT DEFAULT 'website',
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT leads_email_phone_unique UNIQUE (email, phone)
);
